import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: '#f8f8f8',
    },
    card: {
        position: 'absolute',
        top: 0,
        width: '90%',
        height: '32%',
        backgroundColor: '#ffffff',
        borderRadius: 20,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        margin: 45,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    secondCard: {
        position: 'absolute',
        top: '35%', 
        width: '90%',
        height: '35%',
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        margin: 35,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    row: {
        flexDirection: 'row',
        marginVertical: 5,
        justifyContent: 'space-around',
      },
    buttonRow: {
        position: 'absolute',
        top: '70%', 
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '90%',
        marginTop: 60,
    },
    heading: {
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
        color: '#333',
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 8,
    },
    icon: {
        width: 24,
        height: 24,
        marginRight: 10,
        resizeMode: 'contain', 
    },
    infoText: {
        fontSize: 16,
        marginLeft: 10,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
    },
    label: {
        marginLeft: 10,
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        width: 150, 
      },
      description: {
        fontSize: 16,
        color: '#555',
        flex: 1, 
      },
    button: {
        backgroundColor: '#5800EB',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        width: '45%',
        height: 40,
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    logoutButton: {
        position: 'absolute',
        right: 20,
        paddingVertical: 8,
        paddingHorizontal: 15,
        borderRadius: 5,
      },
      logoutText: {
        color: '#0080ff',
        fontSize: 20,
        fontWeight: 'bold',
      },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    viewMoreButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginTop:5,
        borderRadius: 10,
        alignItems: 'center',
      },
      viewMoreText: {
        color: '#007bff',
        fontWeight: 'bold',
        fontSize: 16
      },
      noDataText: {
        fontSize: 16,
        color: 'gray',
        textAlign: 'center',
        marginTop: 10,
      },
});